version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: [mongo_data:/data/db]

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    ports: ["9000:9000", "9001:9001"]
    volumes: [minio_data:/data]

volumes:
  mongo_data:
  minio_data:
